### ISSUE TITLE
Tutorial Jupyter Notebook

### ISSUE THREAD

**Issue by exowanderer** [jasonfrowe/JWSTNIRISS#22]
I am trying to run your tutorial notebook: "Examples and Checks.ipynb".

But the package cannot find the "robustfit" module.

I see that robustfit is a fortran package in the "ramps2slopes" directory and that I need to install it using f2py3.5.  

```
f2py3.5 -m robustfit -h robustfit.pyf precision.f90 robustfit.f90 medfit.f
f2py3.5 --fcompiler=intelem -c robustfit.pyf precision.f90 robustfit.f90 medfit.f
```

The first line works, but the second line fails every time.  I have tried several different pathways to solve this, but cannot get the module to install.  

If I use f2py3.5 with the `--fcompiler=intelem`, then I receive an error that says

`numpy.distutils.fcompiler.CompilerNotFound: intelem: f90 nor f77`

That sort of makes sense. I suppose that I don't have the intel version of f90 installed. But if I remove the and just use `--fcompiler=intelem`

`f2py3.5 -c robustfit.pyf precision.f90 robustfit.f90 medfit.f`

then I receive the following error:

```fortran
medfit.f:98:50:

          if (abs(d).gt.EPS) sum=sum+x(j)*sign(1.0,d)
                                                  1
Error: ‘b’ argument of ‘sign’ intrinsic at (1) must be the same type and kind as ‘a’
```

That might be workable, but I can't read fortran well enough to know how to fix it.

Do you have any suggestions?  I don't have write permissions to this machine, so I cannot install icc or whatever intel package the version of "f90" that you use comes with.

Thank you.

**Comment by jasonfrowe** [comment]
Looks like gfortran is being picky.  It's treating 1.0 as single precision and 'd' as double.  I'm pushing a simple fix:
if (abs(d).gt.EPS) sum=sum+x(j)*sign(1.0d0,d)
changing '1.0' to '1.0d0' to explicitly state that both arguments are double

**Comment by jasonfrowe** [comment]
Pushed change.  Let me know if you have any other issues.

**Comment by exowanderer** [comment]
Yes! That indeed worked. Thank you!

----
But -- there's always a but 😢  -- I had to create a symbolic link named `robustfit.so`.  

This could be an OSX vs LINUX thing though; `gfortran` created 2 files, which were named `robustfit.cpython-35m-darwin.so` and `robustfit.cpython-35m-darwin.so.dSYM`. 

I made a very simple hack:

`ln -s robustfit.cpython-35m-darwin.so robustfit.so`

and I was able to `import robustfit` successfully

----
Then I received a similar `ImportError` for `tracetools`.  I applied a the same hack in `JWSTNIRISS/trace`:

```bash
cd ../trace/
ln -s tracetools.cpython-35m-darwin.so tracetools.so
```

After that, `import jwstniriss as jw` ran completely smoothly.

**Comment by exowanderer** [comment]
On a completely unrelated and trivial note:

On `line [9]` of `Examples and Checks.ipynb`, I had to assigned `image  = scidata[4,:,:]`. Afterwards the entire notebook ran smoothly.

Thank you!

**Comment by exowanderer** [comment]
Side question, why do you provide the `tracetools.pyf` but not the `robustfit.pyf`?  

I am asking my real question in reverse: why not let the user create `tracetools.pyf`, because (I assume) then it might be more stable across platforms. Note that I do not understand fortran or f2py; and my system had no problem using tracetools.pyf. So this is certainly a moot issue.

But I would not have questioned using the following command:

```bash
f2py3.5 -m tracetools -h tracetools.pyf tracetools.f90
```

or something similar.

**Comment by jasonfrowe** [comment]
I'm glad the code fix worked.

I should note that this project is still under development. So not all of the files are available yet.  For example, I'm about a week away from pushing the code based that allows for simulation of SOSS-NIRISS data and about 2 months from finishing the multi-wavelength transit code to model extracted spectra.

**Comment by exowanderer** [comment]
Excellent. I just started on the NIRISS team at STScI and was asked to make simulated transit observations using a suite of code options. Your code was the top of the list.  So I started there. 

We can take this conversation off of the issues channel if you'd like, but I'd be interested to collaborate with you on this.

Do you have any recommendations/"words of caution" for wrapping your code into a simulated transpec?
